### ISSUE TITLE
"CRC or size mismatch" when extracting member second time

### ISSUE THREAD

**Issue by AGWA** [redhotpenguin/perl-Archive-Zip#11]
If I try to extract the same member more than once, the second extraction results in:

```
format error: CRC or size mismatch while skipping data descriptor 
 at /tmp/perl-Archive-Zip/lib/Archive/Zip/ZipFileMember.pm line 192
        Archive::Zip::ZipFileMember::_skipLocalFileHeader('Archive::Zip::ZipFileMember=HASH(0x19e0af0)') called at /tmp/perl-Archive-Zip/lib/Archive/Zip/ZipFileMember.pm line 395
        Archive::Zip::ZipFileMember::rewindData('Archive::Zip::ZipFileMember=HASH(0x19e0af0)') called at /tmp/perl-Archive-Zip/lib/Archive/Zip/Member.pm line 1023
        Archive::Zip::Member::extractToFileHandle('Archive::Zip::ZipFileMember=HASH(0x19e0af0)', 'IO::File=GLOB(0x1ac32f8)') called at /tmp/perl-Archive-Zip/lib/Archive/Zip/Member.pm line 506
        Archive::Zip::Member::extractToFileNamed('Archive::Zip::ZipFileMember=HASH(0x19e0af0)', 'zipout2') called at ./crc_error.pl line 12
```

This only happens with some Zip files.  It seems to happen consistently with Zip files created with the jar command.

Here is a [test case](https://www.cloudmutt.com/s/archive_zip_crc_error/testcase.pl):

```perl
#!/usr/bin/perl

use Archive::Zip;

my $zip = Archive::Zip->new($ARGV[0]);
my $member = $zip->memberNamed('FILE');
$member->extractToFileNamed("zipout1");
$member->extractToFileNamed("zipout2");
```

* Zip file that triggers the bug (created with the jar command): [bad.zip](https://www.cloudmutt.com/s/archive_zip_crc_error/bad.zip)
* Zip file that does not trigger the bug (contains the same contents as bad.zip but was created with InfoZip):  [good.zip](https://www.cloudmutt.com/s/archive_zip_crc_error/good.zip)

I tracked the problem down to `_writeData` modifying `compressedSize` on [line 1103 of lib/Archive/Zip/Member.pm](https://github.com/redhotpenguin/perl-Archive-Zip/blob/4ad0e8366844cd91a368b6ea3188f70f93f14671/lib/Archive/Zip/Member.pm#L1103):

```perl
 $self->{'compressedSize'} = $self->_writeOffset();
```

Because `compressedSize` has been modified, the next time that the member is extracted, `_skipLocalFileHeader` will seek an incorrect number of bytes on [line 175 of lib/Archive/Zip/ZipFileMember.pm](https://github.com/redhotpenguin/perl-Archive-Zip/blob/4ad0e8366844cd91a368b6ea3188f70f93f14671/lib/Archive/Zip/ZipFileMember.pm#L175):

```perl
 $self->fh()->seek($self->{'compressedSize'}, IO::Seekable::SEEK_CUR)
```

I don't understand why `compressedSize` is being set in `_writeData` to what is essentially the *un*compressed length of the member.  If I remove that line, the bug is fixed and Archive::Zip's test suite still passes.  Of course, there may be a good reason for that line that I'm not aware of, which is why I'm not submitting a patch.  What do you think the correct fix is?

Thanks!

**Comment by redhotpenguin** [comment]
Ok would you mind putting together a pull request that implements this so I can evaluate it?

**Comment by redhotpenguin** [comment]
Thanks for the patch - I'll try to add a test and release.

**Comment by pwr22** [comment]
@AGWA Can you state on here that you release your test code and archives (these in particular) under the same licensing terms as Archive::Zip? This is silly to have to ask but I've seen this trip up acceptance of this sort of stuff into upstream linux distros *cough* Debian *cough*

**Comment by AGWA** [comment]
@pwr22 Thanks for working on this.  Yes, I do release my test code and archives under the same licensing terms as Archive::Zip.

**Comment by redhotpenguin** [comment]
@pwr22 @AGWA thank you guys so much for providing this. 1.46 is going out tonight with these changes.
