### ISSUE TITLE
Several problems in "make test"

### ISSUE THREAD

**Issue by farblos** [redhotpenguin/perl-Archive-Zip#54]
There are a number of problems in the current test suite (1.66 + some PRs):

- there are tests `t/26_symlink.t` and `t/26_bug_26.t`.  One of them should be renumbered for clarity.

- test `t/26_bug_26.t` is not mentioned in `MANIFEST` and not packaged, hence

- test `t/26_bug_26.t` fails for yet unknown reasons

- in Travis (e.g. [Job #26.1](https://travis-ci.com/redhotpenguin/perl-Archive-Zip/jobs/237392836) of pull request 53), `common.pm` moans that "zip doesn't seem to work". While that does not let fail any tests, it potentially skips essential ones

While look into these ASAP.

**Comment by farblos** [comment]
Can reproduce failing test `t/26_bug_26.t` locally but don't have the time to look into more details now. @pmqs, any opinion on that one?

No idea yet what to do about last problem ("zip doesn't seem to work") but to add diagnostic output.

**Comment by pmqs** [comment]
> 
> * there are tests `t/26_symlink.t` and `t/26_bug_26.t`.  One of them should be renumbered for clarity.
> * test `t/26_bug_26.t` is not mentioned in `MANIFEST` and not packaged, hence



Created PR #55 to address the issues above.

**Comment by pmqs** [comment]
> Can reproduce failing test `t/26_bug_26.t` locally but don't have the time to look into more details now. @pmqs, any opinion on that one?

will try to get a look at.

> No idea yet what to do about last problem ("zip doesn't seem to work") but to add diagnostic output.

I'm not seeing that error.

**Comment by farblos** [comment]
> I'm not seeing that error.

Agreed.  Must have been an intermittent issue, to be seen only in the one log file I've quoted above.

**Comment by farblos** [comment]
>     * test `t/26_bug_26.t` fails for yet unknown reasons

@pmqs: Seems that the zip64 PR #45 has thrown out the changes in `Member.pm` of your bzip compression commit 9122328b9e187de23c1e4d1be5d6259cefa9248e. (I remember having eliminated parameter `$mode` to function `head` because the only value ever passed to that method before commit 9122328b9e187de23c1e4d1be5d6259cefa9248e was 1.)

I guess that this could be the root cause, but don't have time to validate it now.

Um, probably you could add a one-liner to test `26_bzip.t` in your PR #54 to provide more details what the test should actually do?

**Comment by pmqs** [comment]
> @pmqs: Seems that the zip64 PR #45 has thrown out the changes in `Member.pm` of your bzip compression commit [9122328](https://github.com/redhotpenguin/perl-Archive-Zip/commit/9122328b9e187de23c1e4d1be5d6259cefa9248e). (I remember having eliminated parameter `$mode` to function `head` because the only value ever passed to that method before commit [9122328](https://github.com/redhotpenguin/perl-Archive-Zip/commit/9122328b9e187de23c1e4d1be5d6259cefa9248e) was 1.)
> 
> I guess that this could be the root cause, but don't have time to validate it now.

yes, I that is exactly why the test is failing. 

> Um, probably you could add a one-liner to test `26_bzip.t` in your PR #54 to provide more details what the test should actually do?

Done

**Comment by redhotpenguin** [comment]
Thanks. Will push 1.67 this weekend.

**Comment by redhotpenguin** [comment]
Sorry - maybe I read too fast here. Looks like there's still some investigation going. LMK when a release is needed.

**Comment by farblos** [comment]
To summarize, we have the following issues and PRs that I consider worth including in the next release:

- this issue, fixed by pmqs' PR #55 and #57 

- issue #51, fixed by PR #53 

- issue #56

**Comment by pmqs** [comment]
> To summarize, we have the following issues and PRs that I consider worth including in the next release:
> 
> * this issue, fixed by pmqs' PR #55 and #57
> * issue #51, fixed by PR #53
> * issue #56

Agree

**Comment by farblos** [comment]
All problems fixed in version 1.67.
