### ISSUE TITLE
Extend GitHub test actions on A::Z to also run parallel, shuffled tests

### ISSUE THREAD

**Issue by farblos** [redhotpenguin/perl-Archive-Zip#79]
@pmqs: In `.travis.yml` I have added the following some time ago:

```
   # run tests twice.  First in serial, non-shuffled order to get
   # readable output, then in parallel and shuffled.  Leave
   # verbose mode off for both runs since in automated test
   # environments the tests are verbose already by default.
   - prove -lr $(test-dirs) && prove -lrs -j$((SYSTEM_CORES + 1)) $(test-dirs)
```

Since parallel/shuffled mode has the potential to reveal more problems, this seems to be a good thing.

Do you think anything like that would be also possible with your GitHub actions?

**Comment by pmqs** [comment]
@farblos that is certainly possible if you think it would help. 

According to [this page](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) all GitHub runners have 2 cores. Don't see an environment variable available  for it in the docs, so can probably hard-wire it to use this

    prove -lrs -j2 $(test-dirs)

**Comment by farblos** [comment]
> @farblos that is certainly possible if you think it would help.

The 1.68 CPAN test runs have revealled two nice race conditions when executed in parallel, so there is always a chance of finding something.  The problem with these is, of course, that actually someone has to follow up on seemingly exceptional failures...

> so can probably hard-wire it to use this `prove -lrs -j2 $(test-dirs)`

Agreed.  Thanks!

**Comment by pmqs** [comment]
See https://github.com/redhotpenguin/perl-Archive-Zip/pull/80 for the update

**Comment by farblos** [comment]
Thanks again!
